name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  benchmark-json-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: hiago-balbino/hgz-protobuffer-comparison
          path: ./.github/actions/hgz-protobuffer-comparison

      - name: Run JSON benchmark tests
        run: cd ./.github/actions/hgz-protobuffer-comparison && make json-bench

  benchmark-protobuf-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: hiago-balbino/hgz-protobuffer-comparison
          path: ./.github/actions/hgz-protobuffer-comparison

      - name: Run Protocol Buffer benchmark tests
        run: cd ./.github/actions/hgz-protobuffer-comparison && make proto-bench

  static-check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: hiago-balbino/hgz-protobuffer-comparison
          path: ./.github/actions/hgz-protobuffer-comparison

      - name: Install Static Check on JSON project
        run: cd ./.github/actions/hgz-protobuffer-comparison && cd json && go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Install Static Check on Protobuffer project
        run: cd ./.github/actions/hgz-protobuffer-comparison && cd protobuffer && go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Static Check on JSON project
        run: cd ./.github/actions/hgz-protobuffer-comparison && cd json && staticcheck ./...

      - name: Run Static Check on Protobuffer project
        run: cd ./.github/actions/hgz-protobuffer-comparison && cd protobuffer && staticcheck ./...